### ISSUE TITLE
Connected to ES even though ES is turned off

### ISSUE THREAD

**Issue by MuadDib** [EventStore/EventStoreDB-Client-Dotnet-Legacy#36]
**Describe the bug**
EventStore.ConnectAsync() call succeeds even though EventStore itself is not available.

**To Reproduce**
1. Kill local Event Store process (port 1113)
2. Create new connection
                eventStoreConnectionString = "ConnectTo=tcp://admin:changeit@localhost:1113; HeartBeatTimeout=500;";
                _connection = EventStoreConnection.Create(eventStoreConnectionString);
3. Connect to EventStore
                await _connection.ConnectAsync();

**Expected behavior**
ConnectAsync() should throw exception.

**Actual behavior**
ConnectAsync() is executed without error. The first place where it actually throws exception is during the write itself (_connection.AppendToStreamAsync(stream, expectedVersion, eventData))

I tried adding "ValidateServer=True; FailOnNoServerResponse=True" to connection string but to no avail.

**EventStore details**
 - EventStore server version: 4.1.1.0 (oss-v4.1.1-hotfix1/cd0eafec71baffbcc0b9a4bb7c58e996cf290d34)

 - Operating system: Win10

 - EventStore client version (if applicable): .Net EventStore.Client 5.0.6

**Additional context**

**Comment by oskardudycz** [comment]
Unfortunately, that's expected behaviour, the connection is checked at the first operation call unless you're connecting to a cluster, then the connection will fail if the cluster is down. If you're using version v5 then you can enable `GossipOnSingleNode` setting and use gossip seed instead of TCP scheme, then TCP client will try to run discovery and will fail on that. From v21.10 `GossipOnSingleNode` is enabled by default.

As .NET TCP Client is considered legacy, we won't be changing it, as it's a breaking change.
